[build]
  # The base directory of the `demo-app` app relative to the root of the monorepo
  base = "apps/demo-app"
  # The build command for Nuxt
  command = "npm run build"
  # The directory where Nuxt outputs the built files
  publish = "dist"

# Optional caching to speed up builds
[build.environment]
  NODE_VERSION = "22" # Ensure this matches your Node.js version

[context.production]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/demo-app || git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF base-layer || git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF package.json || git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF turbo.json"
